apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xpo-logistics-prod

resources:
  - ../../base

images:
  - name: projekt-api
    newTag: prod
  - name: projekt-frontend
    newTag: prod

patches:
  - target:
      version: v1
      kind: Namespace
      name: xpo-logistics
    patch: |-
      - op: replace
        path: /metadata/name
        value: xpo-logistics-prod
  - path: api-patch.yaml
  - path: frontend-patch.yaml
  - path: ingress-patch.yaml
  - path: pdb-patch.yaml
