import assert from 'node:assert/strict';
import test from 'node:test';

const loadConfig = async (runtimeConfig, origin, label) => {
  globalThis.window = {
    __XPO_CONFIG__: runtimeConfig,
    location: { origin },
  };

  const module = await import(`../src/oauthConfig.js?case=${label}`);
  return module.oauthConfig;
};

test('oauthConfig uses Google OAuth defaults and localhost redirect URI', async () => {
  const config = await loadConfig(
    {
      PUBLIC_APP_URL: 'http://localhost',
      VITE_API_BASE: 'http://localhost',
      VITE_OAUTH_CLIENT_ID: 'google-client-id.apps.googleusercontent.com',
    },
    'http://localhost:8080',
    'google-defaults'
  );

  assert.equal(config.apiBase, 'http://localhost');
  assert.equal(config.authorizationEndpoint, 'https://accounts.google.com/o/oauth2/v2/auth');
  assert.equal(config.clientId, 'google-client-id.apps.googleusercontent.com');
  assert.equal(config.redirectUri, 'http://localhost/oauth/callback');
  assert.equal(config.googleRedirectUri, 'http://localhost/oauth/callback');
  assert.equal(config.scope, 'openid email profile');
});

test('oauthConfig accepts runtime overrides generated by nginx config.js', async () => {
  const config = await loadConfig(
    {
      PUBLIC_APP_URL: 'http://localhost',
      VITE_API_BASE: 'http://localhost',
      VITE_OAUTH_TOKEN_PATH: '/api/auth/token',
      VITE_OAUTH_REDIRECT_URI: 'http://localhost/oauth/callback',
      VITE_OAUTH_SCOPE: 'openid email profile',
    },
    'http://localhost',
    'runtime-overrides'
  );

  assert.equal(config.tokenPath, '/api/auth/token');
  assert.equal(config.redirectUri, 'http://localhost/oauth/callback');
  assert.equal(config.scope, 'openid email profile');
});
